package endpoint

const (
	AccountCartServiceGetCart                          = "/IAccountCartService/GetCart/v1/"
	AccountCartServiceDeleteCart                       = "/IAccountCartService/DeleteCart/v1/"
	BillingServiceGetRecurringSubscriptionsCount       = "/IBillingService/GetRecurringSubscriptionsCount/v1/"
	CommunityServiceGetApps                            = "/ICommunityService/GetApps/v1/"
	FamilyGroupsServiceGetChangeLog                    = "/IFamilyGroupsService/GetChangeLog/v1/"
	FamilyGroupsServiceGetFamilyGroup                  = "/IFamilyGroupsService/GetFamilyGroup/v1/"
	FamilyGroupsServiceGetFamilyGroupForUser           = "/IFamilyGroupsService/GetFamilyGroupForUser/v1/"
	FamilyGroupsServiceGetPlaytimeSummary              = "/IFamilyGroupsService/GetPlaytimeSummary/v1/"
	FamilyGroupsServiceGetSharedLibraryApps            = "/IFamilyGroupsService/GetSharedLibraryApps/v1/"
	LoyaltyRewardsServiceGetEquippedProfileItems       = "/ILoyaltyRewardsService/GetEquippedProfileItems/v1/"
	LoyaltyRewardsServiceGetReactionsSummaryForUser    = "/ILoyaltyRewardsService/GetReactionsSummaryForUser/v1/"
	LoyaltyRewardsServiceGetSummary                    = "/ILoyaltyRewardsService/GetSummary/v1/"
	MobileNotificationServiceGetUserNotificationCounts = "/IMobileNotificationService/GetUserNotificationCounts/v1/"
	NewsServiceConvertHTMLToBBCode                     = "/INewsService/ConvertHTMLToBBCode/v1/"
	PlayerServiceClientGetLastPlayedTimes              = "/IPlayerService/ClientGetLastPlayedTimes/v1/"
	PlayerServiceGetAchievementsProgress               = "/IPlayerService/GetAchievementsProgress/v1/"
	PlayerServiceGetAnimatedAvatar                     = "/IPlayerService/GetAnimatedAvatar/v1/"
	PlayerServiceGetAvatarFrame                        = "/IPlayerService/GetAvatarFrame/v1/"
	PlayerServiceGetBadges                             = "/IPlayerService/GetBadges/v1/"
	PlayerServiceGetCommunityBadgeProgress             = "/IPlayerService/GetCommunityBadgeProgress/v1/"
	PlayerServiceGetCommunityPreferences               = "/IPlayerService/GetCommunityPreferences/v1/"
	PlayerServiceGetFavoriteBadge                      = "/IPlayerService/GetFavoriteBadge/v1/"
	PlayerServiceGetFriendsGameplayInfo                = "/IPlayerService/GetFriendsGameplayInfo/v1/"
	PlayerServiceGetMiniProfileBackground              = "/IPlayerService/GetMiniProfileBackground/v1/"
	PlayerServiceGetNicknameList                       = "/IPlayerService/GetNicknameList/v1/"
	PlayerServiceGetPlayerLinkDetails                  = "/IPlayerService/GetPlayerLinkDetails/v1/"
	PlayerServiceGetProfileBackground                  = "/IPlayerService/GetProfileBackground/v1/"
	PlayerServiceGetProfileCustomization               = "/IPlayerService/GetProfileCustomization/v1/"
	PlayerServiceGetProfileItemsEquipped               = "/IPlayerService/GetProfileItemsEquipped/v1/"
	PlayerServiceGetProfileItemsOwned                  = "/IPlayerService/GetProfileItemsOwned/v1/"
	PlayerServiceGetProfileThemesAvailable             = "/IPlayerService/GetProfileThemesAvailable/v1/"
	SteamUserGetPlayerSummaries                        = "/ISteamUser/GetPlayerSummaries/v2/"
	PlayerServiceGetOwnedGames                         = "/IPlayerService/GetOwnedGames/v1/"
	SteamNewsGetNewsForApp                             = "/ISteamNews/GetNewsForApp/v2/"
	SteamUserStatsGetPlayerAchievements                = "/ISteamUserStats/GetPlayerAchievements/v1/"
)
